"""Pet table creation

Revision ID: 40aa70444ffa
Revises: 
Create Date: 2023-02-01 15:35:19.983983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40aa70444ffa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('pet_breed', sa.Text(), nullable=True),
    sa.Column('pet_name', sa.Text(), nullable=True),
    sa.Column('pet_owner', sa.Text(), nullable=True),
    sa.Column('pet_age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
